[package]
name = "exfat"
version = "0.1.0"
edition = "2021"
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
repository = "https://github.com/qiuchengxuan/exfat"
keywords = ["fat", "exfat", "filesystem", "no_std", "async"]
categories = ["filesystem"]
license = "MIT"
description = "ExFAT filesystem library with async support"

[dependencies]
async-std = { version = "1.11", optional = true }
async-trait = "0.1"
bitfield = "0.13"
chrono = { version = "0.4", optional = true, default-features = false }
deasync = "0.1"
heapless = "0.7"
hex-literal = "0.3"
log = "0.4"

[features]
alloc = []
async = ["deasync/bypass"]
std = ["async-std"]
default = ["alloc"]
