[package]
name = "embedded-exfat"
version = "0.1.1"
edition = "2021"
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
repository = "https://github.com/qiuchengxuan/exfat"
keywords = ["fat", "exfat", "filesystem", "no_std", "async"]
categories = ["filesystem"]
license = "MIT"
description = "ExFAT filesystem library with async support, mainly focusing on embedded system"

[dependencies]
async-std = { version = "1.12", optional = true }
async-trait = "0.1"
bitfield = "0.13"
chrono = { version = "0.4", optional = true, default-features = false }
deasync = "0.1"
derive_more = "0.99"
fast-async-mutex = { version = "0.6", optional = true }
heapless = "0.7"
hex-literal = "0.3"
log = "0.4"
memoffset = "0.8"
spin-sync = "0.3"

[features]
async = ["fast-async-mutex"]
std = ["async-std"]
default = ["std"]
log-max-level-off = ["log/max_level_off", "log/release_max_level_off"]

[lib]
name = "exfat"
